application: tulip
http:
  port: 8010
data:
  sql: refGene.sql
  refGene: refGene.txt
  dbname: hg38

# databases
databases:
  - dsn: root:vmware@(localhost:3306)/hg38
    switch: off
  - dsn: root:togerme@(gene_db:3306)/hg38
    switch: on
